apiVersion: vick.wso2.com/v1alpha1
kind: Cell
metadata:
  name: hr
spec:
  gatewayTemplate:
    spec:
      apis:
      - context: info
        definitions:
        - path: /
          method: GET
        backend: hr-service
        global: true
  servicesTemplates:
  - metadata:
      name: hr
    spec:
      replicas: 1
      container:
        image: docker.io/wso2vick/sampleapp-hr:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: employeegw_url
          value: employee--gateway-service
        - name: stockgw_url
          value: stock-options--gateway-service
          stock-options--stock-service
      servicePort: 80
