apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cells.vick.wso2.com
spec:
  group: vick.wso2.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cell
    plural: cells
    singular: cell
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.status
  - name: Gateway
    type: string
    description: Host name of the gateway
    JSONPath: .status.gatewayHostname
  - name: Services
    type: integer
    description: Number of services in this cell
    JSONPath: .status.serviceCount
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
