apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.vick.wso2.com
spec:
  group: vick.wso2.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Gateway
    plural: gateways
    singular: gateway
    shortNames:
    - vgateways
    - vgw
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.status
  - name: Hostname
    type: string
    description: Host name of the gateway
    JSONPath: .status.hostname
  - name: Cell
    type: string
    description: Owner cell of this gateway
    JSONPath: .status.ownerCell
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
