apiVersion: v1
data:
  cell-gateway-config: |
    {
        "username": "admin",
        "password": "admin",
        "apiVersion": "v0.14",
        "registerPayload": {
            "clientName": "rest_api_publisher",
            "owner": "admin",
            "grantType": "password refresh_token",
            "saasApp": true
        },
        "apimBaseUrl": "https://10.100.1.247:9443",
        "tokenEndpoint": "https://10.100.1.247:8243/token",
        "trustStore": {
            "location": "lib/platform/bre/security/ballerinaTruststore.p12",
            "password": "ballerina"
        }
    }
  cell-gateway-init-image: wso2vick/cell-gateway-init
  cell-gateway-image: wso2vick/cell-gateway
  cell-sts-config: |
    {
        "endpoint": "https://10.100.1.217:9443/api/identity/vick-auth/v1.0/sts/token",
        "username": "admin",
        "password": "admin"
    }
  cell-sts-image: wso2vick/cell-sts:latest
kind: ConfigMap
metadata:
  name: vick-config
  namespace: vick-system
