apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apim-repository-deployment-server-pvc
  namespace: vick-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: apim-repository-deployment-server
