apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cells.vick.wso2.com
spec:
  group: vick.wso2.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cell
    plural: cells
    singular: cell
